#ifndef			SDLAZY_CURSORSASCII
# define		SDLAZY_CURSORSASCII

static const char*	cur_arrow[] =
  {
    "X                               ",
    "XX                              ",
    "X.X                             ",
    "X..X                            ",
    "X...X                           ",
    "X....X                          ",
    "X.....X                         ",
    "X......X                        ",
    "X.......X                       ",
    "X........X                      ",
    "X.........X                     ",
    "X..........X                    ",
    "X......XXXXXX                   ",
    "X...X..X                        ",
    "X..X X..X                       ",
    "X.X  X..X                       ",
    "XX    X..X                      ",
    "X     X..X                      ",
    "       XX                       ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                "
  };

static const char*      cur_pointer[] =
  {
    "    XX                          ",
    "   X..X                         ",
    "   X..X                         ",
    "   X..X                         ",
    "   X..XXX                       ",
    "   X..X..XXX                    ",
    "   X..X..X..XXX                 ",
    " XXX.....X..X..X                ",
    "X..X...........X                ",
    "X..X...........X                ",
    "X..X...........X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    " XXXXXXXXXXXXXX                 ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                "
  };

static const char*      cur_open_hand[] =
  {
    "       XX                       ",
    "    XXX..XXX                    ",
    "   X..X..X..X                   ",
    "   X..X..X..XXX                 ",
    "   X..X..X..X..X                ",
    " XXX..X........X                ",
    "X..X...........X                ",
    "X..X...........X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    " XXXXXXXXXXXXXX                 ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                "
  };

static const char*      cur_close_hand[] =
  {
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "       XX                       ",
    "    XXX..XXX                    ",
    "   X..X..X..X                   ",
    " XXX..X..X..XXXX                ",
    "X..X........X..X                ",
    "X..X...........X                ",
    "X..X...........X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    "X..............X                ",
    " X.............X                ",
    "  XXXXXXXXXXXXX                 ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                "
  };

static const char*	cur_cross[] =
  {
    "        XXX                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "XXXXXXXXX.XXXXXXXXX             ",
    "X.................X             ",
    "XXXXXXXXX.XXXXXXXXX             ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        X.X                     ",
    "        XXX                     ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                ",
    "                                "
  };

#endif
